spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

jwt:
  secret-key-source: ${JWT_SECRET_KEY}

logging:
  level:
    org.hibernate.type: trace
    com.app: debug

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: ${S3_BUCKET}
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

default:
  profile:
    image: ${DEFAULT_PROFILE_IMAGE}