name: Deploy to cloudtype

# on : Event에 대해 작성하는 부분. main에 push가 올 경우
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# jobs : 여러 스텝으로 실행. 스텝은 프로세스의 단위. 
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest #어떤 OS에서 실행될지 지정
    
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2 #해당 스텝에서 사용할 액션. {owner}/{repo}@{ref|version}의 형태

      # 클라우드 타입
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
          
      - name: Deploy
          uses: cloudtype-github-actions/deploy@v1
          with:
            token: ${{ secrets.CLOUDTYPE_TOKEN }}
            project: super-backend/talktudy
            stage: main
            yaml: >
              name: talktudy-backend
              
              app: java@11
              
              options:
                ports: "8080"
                env:
                  - name: SPRING_PROFILES_ACTIVE
                    value: prod
                  - name: DEFAULT_PROFILE_IMAGE
                    value: https://talktudy.s3.ap-northeast-2.amazonaws.com/dfimg.jpeg
                  - name: DATABASE_PASSWORD
                    secret: DATABASE_PASSWORD
                  - name: DATABASE_URL
                    secret: DATABASE_URL
                  - name: DATABASE_USERNAME
                    secret: DATABASE_USERNAME
                  - name: JWT_SECRET_KEY
                    secret: JWT_SECRET_KEY
                  - name: S3_ACCESS_KEY
                    secret: S3_ACCESS_KEY
                  - name: S3_BUCKET
                    secret: S3_BUCKET
                  - name: S3_SECRET_KEY
                    secret: S3_SECRET_KEY
              context:
                git:
                  url: git@github.com:${{ github.repository }}.git
                  ref: ${{ github.ref }}